#!/usr/bin/env bash
# Install nginx on your web-01 server

sudo apt-get update
sudo apt-get install nginx -y
sudo touch "/var/www/html/index.html"
echo "Holberton School" | sudo tee "/var/www/html/index.html"
sudo service nginx restart
