#!/usr/bin/env bash
# Bash scripts installs nginx on a web server
# and redirects and error 404
sudo apt-get update
sudo apt-get install nginx -y
echo "Holberton School" | sudo tee "/var/www/html/index.html"
cmd="\\\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
# set permanent redirect using command
sudo sed -i "/server_name _;/a $cmd" /etc/nginx/sites-available/default
# custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
cstm_404="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "49i $cstm_404" /etc/nginx/sites-available/default
sudo service nginx restart
