#!/usr/bin/env bash
# Install nginx on your web-01 server

sudo apt-get update
sudo apt-get install nginx -y
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee "/var/www/html/index.html"
command='\\\trewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'
sudo sed -i "42i$command" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
cstm_404="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "49i $cstm_404" /etc/nginx/sites-available/default
sudo service nginx restart
