#!/usr/bin/env bash
# configure web-02 to be identical to web-01

sudo apt-get update
sudo apt-get install nginx -y

string='add_header X-Served-By "$hostname" always;'
sudo sed -i "56i \\\t$string" /etc/nginx/sites-available/default

sudo service nginx restart
