#!/usr/bin/env bash
# Bash script that gives information about the holbertonschool file

FILE=holbertonschool
if test -f "$FILE"; then
	echo "$FILE file exists"

	if [ -s "$FILE" ]
	then
		echo "$FILE is not empty"
	else
		echo "$FILE is empty"
	fi

	echo "$FILE is a regular file"

else
	echo "$FILE file does not exist"
fi
